# Generated by Django 4.1 on 2022-08-08 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 8, 14, 0, 9, 487142, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
