# Generated by Django 4.1 on 2022-08-11 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0004_alter_customuser_options_remove_customuser_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=31,
                validators=[django.core.validators.RegexValidator("^\\+38\\d{10}$")],
            ),
        ),
    ]
