# Generated by Django 4.1 on 2022-08-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0005_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
