# Generated by Django 4.1 on 2022-08-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0006_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
