# Generated by Django 4.1 on 2022-08-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0009_alter_request_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="request_id",
            new_name="request",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="price",
            field=models.FloatField(),
        ),
    ]
