# Generated by Django 4.1 on 2022-08-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0010_rename_request_id_invoice_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("UNPAID", "UNPAID"), ("PAID", "PAID")],
                default="UNPAID",
                max_length=30,
            ),
        ),
    ]
